#!/usr/bin/env fish

set -l modinfo (jq -r '.modid,.version' modinfo.json)
set -l modid $modinfo[1]
set -l modversion $modinfo[2]
set -l pkgname {$modid}_$modversion.zip
zip -r $pkgname modinfo.json assets
gh release create v$modversion --fail-on-no-commits $pkgname
